fieldLayouts:
  ffc04180-3a24-4133-9acb-2d7f8511bb57:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 429f5b7c-5307-4067-a224-1599e698c519
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3933bb3f-0272-4f3d-a05c-2d66437a6e52
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
section: 7d2ec9bb-3721-4de3-a6f7-a22c52a85eee # Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
