fieldLayouts:
  9343c105-1247-4ccd-95a6-05016bc24da9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9ff34933-7b09-4dd2-824f-cca77ebf132d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 78af90d6-5374-4395-aaf3-7fa056bbefd0
        userCondition: null
fs: uploads
handle: images
name: images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
