columnSuffix: qjselyjq
contentColumnType: integer(10)
fieldGroup: 0254b196-50ac-4bfa-b010-1f99281ca1b5 # Common
handle: price
instructions: null
name: Price
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
