defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  839dd7f1-0eb7-4069-bdb9-16ffd00a4887: # craft
    enabledByDefault: true
    hasUrls: true
    template: contact/_contacte.twig
    uriFormat: contact
type: single
