defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  839dd7f1-0eb7-4069-bdb9-16ffd00a4887: # craft
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
