defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  839dd7f1-0eb7-4069-bdb9-16ffd00a4887: # craft
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: 'pages/{slug}'
structure:
  maxLevels: 2
  uid: 918c403e-d679-4c39-8059-b5aad80d8f64
type: structure
